import Navbar from "@/components/root_layout/navbar/Navbar";
import ReduxProvider from "@/lib/redux/store_provider/StorePrvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const reqHeaders = headers();
  console.log(reqHeaders.entries());
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <div className="flex gap-8">
            <Navbar />
            {children}
            <Toaster />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
